<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
=======
'use client';

import {ApolloProvider} from '@apollo/client';
import {Inter} from 'next/font/google';
import apolloClient from '@/lib/apollo-client';
import {AuthProvider} from './context/AuthContext';
import './globals.css';

const inter = Inter({subsets: ['latin']});

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ApolloProvider client={apolloClient}>
            <AuthProvider>
                {children}
            </AuthProvider>
        </ApolloProvider>
        </body>
        </html>
    );
}
>>>>>>> e7f18a635fb148293bdfd58472ae72bb9f531ed2
